/*
 * generated by Xtext
 */
package uws.chaudy.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import uws.chaudy.ui.internal.EngageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EngageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EngageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EngageActivator.getInstance().getInjector(EngageActivator.UWS_CHAUDY_ENGAGE);
	}
	
}
