/**
 * generated by Xtext
 */
package uws.chaudy.validation;

import uws.chaudy.validation.AbstractEngageValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class EngageValidator extends AbstractEngageValidator {
}
