/*
* generated by Xtext
*/
package uws.engage.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AssessUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return uws.engage.dsl.ui.internal.AssessActivator.getInstance().getInjector("uws.engage.dsl.Assess");
	}
	
}
