/**
 * generated by Xtext
 */
package uws.engage.dsl.ui.contentassist;

import uws.engage.dsl.ui.contentassist.AbstractAssessProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AssessProposalProvider extends AbstractAssessProposalProvider {
}
