/*
* generated by Xtext
*/
package uws.engage.dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import uws.engage.dsl.services.AssessGrammarAccess;

public class AssessParser extends AbstractContentAssistParser {
	
	@Inject
	private AssessGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected uws.engage.dsl.ui.contentassist.antlr.internal.InternalAssessParser createParser() {
		uws.engage.dsl.ui.contentassist.antlr.internal.InternalAssessParser result = new uws.engage.dsl.ui.contentassist.antlr.internal.InternalAssessParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getTypeAccess().getSimpleTypeAlternatives_0_0(), "rule__Type__SimpleTypeAlternatives_0_0");
					put(grammarAccess.getTypeOutcomeAccess().getAlternatives(), "rule__TypeOutcome__Alternatives");
					put(grammarAccess.getFeedbackAccess().getAlternatives_4(), "rule__Feedback__Alternatives_4");
					put(grammarAccess.getTypeFeedbackAccess().getAlternatives(), "rule__TypeFeedback__Alternatives");
					put(grammarAccess.getActionSequenceAccess().getAlternatives_1(), "rule__ActionSequence__Alternatives_1");
					put(grammarAccess.getTimingAccess().getAlternatives_0(), "rule__Timing__Alternatives_0");
					put(grammarAccess.getActionReactionAccess().getAlternatives(), "rule__ActionReaction__Alternatives");
					put(grammarAccess.getPointsAccess().getAlternatives_2(), "rule__Points__Alternatives_2");
					put(grammarAccess.getPointsAccess().getOthersAlternatives_2_0_0(), "rule__Points__OthersAlternatives_2_0_0");
					put(grammarAccess.getOutcomesPointsAccess().getAlternatives_2(), "rule__OutcomesPoints__Alternatives_2");
					put(grammarAccess.getSignAccess().getAlternatives(), "rule__Sign__Alternatives");
					put(grammarAccess.getParamAccess().getAlternatives(), "rule__Param__Alternatives");
					put(grammarAccess.getBOOLAccess().getAlternatives(), "rule__BOOL__Alternatives");
					put(grammarAccess.getReactionAccess().getAlternatives(), "rule__Reaction__Alternatives");
					put(grammarAccess.getPointsConditionAccess().getAlternatives_2(), "rule__PointsCondition__Alternatives_2");
					put(grammarAccess.getPointsKeyWdAccess().getAlternatives(), "rule__PointsKeyWd__Alternatives");
					put(grammarAccess.getTriggerAccess().getAlternatives(), "rule__Trigger__Alternatives");
					put(grammarAccess.getCompSignAccess().getAlternatives(), "rule__CompSign__Alternatives");
					put(grammarAccess.getGenericTriggerAccess().getAlternatives(), "rule__GenericTrigger__Alternatives");
					put(grammarAccess.getFeedbackKeywordsSimpleAccess().getAlternatives(), "rule__FeedbackKeywordsSimple__Alternatives");
					put(grammarAccess.getFeedbackKeywordsComplexAccess().getAlternatives(), "rule__FeedbackKeywordsComplex__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getEnumAccess().getGroup(), "rule__Enum__Group__0");
					put(grammarAccess.getEnumAccess().getGroup_3(), "rule__Enum__Group_3__0");
					put(grammarAccess.getGameDescriptionAccess().getGroup(), "rule__GameDescription__Group__0");
					put(grammarAccess.getGameDescriptionAccess().getGroup_7(), "rule__GameDescription__Group_7__0");
					put(grammarAccess.getGameDescriptionAccess().getGroup_8(), "rule__GameDescription__Group_8__0");
					put(grammarAccess.getGameDescriptionAccess().getGroup_9(), "rule__GameDescription__Group_9__0");
					put(grammarAccess.getGameDescriptionAccess().getGroup_10(), "rule__GameDescription__Group_10__0");
					put(grammarAccess.getGameDescriptionAccess().getGroup_11(), "rule__GameDescription__Group_11__0");
					put(grammarAccess.getGameDescriptionAccess().getGroup_12(), "rule__GameDescription__Group_12__0");
					put(grammarAccess.getGameDescriptionAccess().getGroup_13(), "rule__GameDescription__Group_13__0");
					put(grammarAccess.getAgeAccess().getGroup(), "rule__Age__Group__0");
					put(grammarAccess.getPlayerDescriptionAccess().getGroup(), "rule__PlayerDescription__Group__0");
					put(grammarAccess.getCharacteristicAccess().getGroup(), "rule__Characteristic__Group__0");
					put(grammarAccess.getLearningOutcomesAccess().getGroup(), "rule__LearningOutcomes__Group__0");
					put(grammarAccess.getOutcomeAccess().getGroup(), "rule__Outcome__Group__0");
					put(grammarAccess.getFeedbackMessagesAccess().getGroup(), "rule__FeedbackMessages__Group__0");
					put(grammarAccess.getFeedbackAccess().getGroup(), "rule__Feedback__Group__0");
					put(grammarAccess.getEvidenceModelAccess().getGroup(), "rule__EvidenceModel__Group__0");
					put(grammarAccess.getActionSequencesAccess().getGroup(), "rule__ActionSequences__Group__0");
					put(grammarAccess.getActionSequenceAccess().getGroup(), "rule__ActionSequence__Group__0");
					put(grammarAccess.getTimerActionsAccess().getGroup(), "rule__TimerActions__Group__0");
					put(grammarAccess.getTimerActionAccess().getGroup(), "rule__TimerAction__Group__0");
					put(grammarAccess.getTimingAccess().getGroup(), "rule__Timing__Group__0");
					put(grammarAccess.getUpdateScoreAccess().getGroup(), "rule__UpdateScore__Group__0");
					put(grammarAccess.getTriggerFeedbackAccess().getGroup(), "rule__TriggerFeedback__Group__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getActionAccess().getGroup_3(), "rule__Action__Group_3__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getPointsAccess().getGroup(), "rule__Points__Group__0");
					put(grammarAccess.getPointsAccess().getGroup_1(), "rule__Points__Group_1__0");
					put(grammarAccess.getOutcomesPointsAccess().getGroup(), "rule__OutcomesPoints__Group__0");
					put(grammarAccess.getOutcomesPointsAccess().getGroup_0(), "rule__OutcomesPoints__Group_0__0");
					put(grammarAccess.getPointAccess().getGroup(), "rule__Point__Group__0");
					put(grammarAccess.getParamsAccess().getGroup(), "rule__Params__Group__0");
					put(grammarAccess.getParamsAccess().getGroup_0(), "rule__Params__Group_0__0");
					put(grammarAccess.getParamsAccess().getGroup_2(), "rule__Params__Group_2__0");
					put(grammarAccess.getFLOATAccess().getGroup(), "rule__FLOAT__Group__0");
					put(grammarAccess.getFLOATAccess().getGroup_1(), "rule__FLOAT__Group_1__0");
					put(grammarAccess.getReactionsAccess().getGroup(), "rule__Reactions__Group__0");
					put(grammarAccess.getReactionAccess().getGroup_1(), "rule__Reaction__Group_1__0");
					put(grammarAccess.getPointsConditionAccess().getGroup(), "rule__PointsCondition__Group__0");
					put(grammarAccess.getFeedbackModelAccess().getGroup(), "rule__FeedbackModel__Group__0");
					put(grammarAccess.getOutcomeValueLimitAccess().getGroup(), "rule__OutcomeValueLimit__Group__0");
					put(grammarAccess.getInactivityLimitAccess().getGroup(), "rule__InactivityLimit__Group__0");
					put(grammarAccess.getBadgeModelAccess().getGroup(), "rule__BadgeModel__Group__0");
					put(grammarAccess.getSimpleTriggerAccess().getGroup(), "rule__SimpleTrigger__Group__0");
					put(grammarAccess.getLOTriggerAccess().getGroup(), "rule__LOTrigger__Group__0");
					put(grammarAccess.getModelAccess().getGameAssignment_0(), "rule__Model__GameAssignment_0");
					put(grammarAccess.getModelAccess().getPlayerAssignment_1(), "rule__Model__PlayerAssignment_1");
					put(grammarAccess.getModelAccess().getLearningOutcomesAssignment_2(), "rule__Model__LearningOutcomesAssignment_2");
					put(grammarAccess.getModelAccess().getFeedbackMessagesAssignment_3(), "rule__Model__FeedbackMessagesAssignment_3");
					put(grammarAccess.getModelAccess().getEvidenceModelAssignment_4(), "rule__Model__EvidenceModelAssignment_4");
					put(grammarAccess.getModelAccess().getFeedbackModelAssignment_5(), "rule__Model__FeedbackModelAssignment_5");
					put(grammarAccess.getModelAccess().getBadgeModelAssignment_6(), "rule__Model__BadgeModelAssignment_6");
					put(grammarAccess.getTypeAccess().getSimpleTypeAssignment_0(), "rule__Type__SimpleTypeAssignment_0");
					put(grammarAccess.getTypeAccess().getEnumTypeAssignment_1(), "rule__Type__EnumTypeAssignment_1");
					put(grammarAccess.getEnumAccess().getEnumValuesAssignment_2(), "rule__Enum__EnumValuesAssignment_2");
					put(grammarAccess.getEnumAccess().getEnumValuesAssignment_3_1(), "rule__Enum__EnumValuesAssignment_3_1");
					put(grammarAccess.getGameDescriptionAccess().getNameAssignment_3(), "rule__GameDescription__NameAssignment_3");
					put(grammarAccess.getGameDescriptionAccess().getDevAssignment_6(), "rule__GameDescription__DevAssignment_6");
					put(grammarAccess.getGameDescriptionAccess().getDescAssignment_7_2(), "rule__GameDescription__DescAssignment_7_2");
					put(grammarAccess.getGameDescriptionAccess().getAgeRangeAssignment_8_2(), "rule__GameDescription__AgeRangeAssignment_8_2");
					put(grammarAccess.getGameDescriptionAccess().getLangAssignment_9_2(), "rule__GameDescription__LangAssignment_9_2");
					put(grammarAccess.getGameDescriptionAccess().getCountryAssignment_10_2(), "rule__GameDescription__CountryAssignment_10_2");
					put(grammarAccess.getGameDescriptionAccess().getGenreAssignment_11_2(), "rule__GameDescription__GenreAssignment_11_2");
					put(grammarAccess.getGameDescriptionAccess().getSubjectAssignment_12_2(), "rule__GameDescription__SubjectAssignment_12_2");
					put(grammarAccess.getGameDescriptionAccess().getPublicAssignment_13_2(), "rule__GameDescription__PublicAssignment_13_2");
					put(grammarAccess.getAgeAccess().getAgeMinAssignment_0(), "rule__Age__AgeMinAssignment_0");
					put(grammarAccess.getAgeAccess().getAgeMaxAssignment_2(), "rule__Age__AgeMaxAssignment_2");
					put(grammarAccess.getPlayerDescriptionAccess().getCharacteristicsAssignment_1(), "rule__PlayerDescription__CharacteristicsAssignment_1");
					put(grammarAccess.getCharacteristicAccess().getNameAssignment_0(), "rule__Characteristic__NameAssignment_0");
					put(grammarAccess.getCharacteristicAccess().getTypeAssignment_2(), "rule__Characteristic__TypeAssignment_2");
					put(grammarAccess.getLearningOutcomesAccess().getOutcomesAssignment_1(), "rule__LearningOutcomes__OutcomesAssignment_1");
					put(grammarAccess.getOutcomeAccess().getNameAssignment_0(), "rule__Outcome__NameAssignment_0");
					put(grammarAccess.getOutcomeAccess().getDescAssignment_1(), "rule__Outcome__DescAssignment_1");
					put(grammarAccess.getOutcomeAccess().getValueAssignment_2(), "rule__Outcome__ValueAssignment_2");
					put(grammarAccess.getOutcomeAccess().getTypeAssignment_3(), "rule__Outcome__TypeAssignment_3");
					put(grammarAccess.getTypeOutcomeAccess().getKnowledgeAssignment_0(), "rule__TypeOutcome__KnowledgeAssignment_0");
					put(grammarAccess.getTypeOutcomeAccess().getSkillAssignment_1(), "rule__TypeOutcome__SkillAssignment_1");
					put(grammarAccess.getTypeOutcomeAccess().getCompetenceAssignment_2(), "rule__TypeOutcome__CompetenceAssignment_2");
					put(grammarAccess.getFeedbackMessagesAccess().getFeedbackMsgsAssignment_1(), "rule__FeedbackMessages__FeedbackMsgsAssignment_1");
					put(grammarAccess.getFeedbackAccess().getNameAssignment_0(), "rule__Feedback__NameAssignment_0");
					put(grammarAccess.getFeedbackAccess().getMessageAssignment_1(), "rule__Feedback__MessageAssignment_1");
					put(grammarAccess.getFeedbackAccess().getImageAssignment_2(), "rule__Feedback__ImageAssignment_2");
					put(grammarAccess.getFeedbackAccess().getTypeAssignment_3(), "rule__Feedback__TypeAssignment_3");
					put(grammarAccess.getFeedbackAccess().getWinAssignment_4_0(), "rule__Feedback__WinAssignment_4_0");
					put(grammarAccess.getFeedbackAccess().getLoseAssignment_4_1(), "rule__Feedback__LoseAssignment_4_1");
					put(grammarAccess.getFeedbackAccess().getEndAssignment_4_2(), "rule__Feedback__EndAssignment_4_2");
					put(grammarAccess.getEvidenceModelAccess().getActionsAssignment_1(), "rule__EvidenceModel__ActionsAssignment_1");
					put(grammarAccess.getEvidenceModelAccess().getTimerActionsAssignment_2(), "rule__EvidenceModel__TimerActionsAssignment_2");
					put(grammarAccess.getEvidenceModelAccess().getActionSequenceAssignment_3(), "rule__EvidenceModel__ActionSequenceAssignment_3");
					put(grammarAccess.getActionSequencesAccess().getActionSequencesAssignment_1(), "rule__ActionSequences__ActionSequencesAssignment_1");
					put(grammarAccess.getActionSequenceAccess().getAction1Assignment_0(), "rule__ActionSequence__Action1Assignment_0");
					put(grammarAccess.getActionSequenceAccess().getBeforeAssignment_1_0(), "rule__ActionSequence__BeforeAssignment_1_0");
					put(grammarAccess.getActionSequenceAccess().getAfterAssignment_1_1(), "rule__ActionSequence__AfterAssignment_1_1");
					put(grammarAccess.getActionSequenceAccess().getAction2Assignment_2(), "rule__ActionSequence__Action2Assignment_2");
					put(grammarAccess.getActionSequenceAccess().getSequenceReactionsAssignment_4(), "rule__ActionSequence__SequenceReactionsAssignment_4");
					put(grammarAccess.getTimerActionsAccess().getTimerActionsAssignment_1(), "rule__TimerActions__TimerActionsAssignment_1");
					put(grammarAccess.getTimerActionAccess().getNameAssignment_0(), "rule__TimerAction__NameAssignment_0");
					put(grammarAccess.getTimerActionAccess().getTimingsAssignment_1(), "rule__TimerAction__TimingsAssignment_1");
					put(grammarAccess.getTimingAccess().getBeforeAssignment_0_0(), "rule__Timing__BeforeAssignment_0_0");
					put(grammarAccess.getTimingAccess().getAfterAssignment_0_1(), "rule__Timing__AfterAssignment_0_1");
					put(grammarAccess.getTimingAccess().getLimitAssignment_1(), "rule__Timing__LimitAssignment_1");
					put(grammarAccess.getTimingAccess().getTimingReactionsAssignment_3(), "rule__Timing__TimingReactionsAssignment_3");
					put(grammarAccess.getActionReactionAccess().getUpdateScoreAssignment_0(), "rule__ActionReaction__UpdateScoreAssignment_0");
					put(grammarAccess.getActionReactionAccess().getTriggerFeedbackAssignment_1(), "rule__ActionReaction__TriggerFeedbackAssignment_1");
					put(grammarAccess.getUpdateScoreAccess().getOutcomeAssignment_0(), "rule__UpdateScore__OutcomeAssignment_0");
					put(grammarAccess.getUpdateScoreAccess().getPtsAssignment_2(), "rule__UpdateScore__PtsAssignment_2");
					put(grammarAccess.getTriggerFeedbackAccess().getFeedbackAssignment_1(), "rule__TriggerFeedback__FeedbackAssignment_1");
					put(grammarAccess.getTriggerFeedbackAccess().getImmediateAssignment_2(), "rule__TriggerFeedback__ImmediateAssignment_2");
					put(grammarAccess.getActionAccess().getNameAssignment_0(), "rule__Action__NameAssignment_0");
					put(grammarAccess.getActionAccess().getParamsAssignment_2(), "rule__Action__ParamsAssignment_2");
					put(grammarAccess.getActionAccess().getParamsAssignment_3_1(), "rule__Action__ParamsAssignment_3_1");
					put(grammarAccess.getActionAccess().getDescAssignment_5(), "rule__Action__DescAssignment_5");
					put(grammarAccess.getActionAccess().getPointsAssignment_6(), "rule__Action__PointsAssignment_6");
					put(grammarAccess.getActionAccess().getReactionsAssignment_7(), "rule__Action__ReactionsAssignment_7");
					put(grammarAccess.getParameterAccess().getLogOnlyAssignment_0(), "rule__Parameter__LogOnlyAssignment_0");
					put(grammarAccess.getParameterAccess().getTypeAssignment_1(), "rule__Parameter__TypeAssignment_1");
					put(grammarAccess.getParameterAccess().getNameAssignment_2(), "rule__Parameter__NameAssignment_2");
					put(grammarAccess.getPointsAccess().getOutcomesPointsAssignment_0(), "rule__Points__OutcomesPointsAssignment_0");
					put(grammarAccess.getPointsAccess().getOutcomesPointsAssignment_1_1(), "rule__Points__OutcomesPointsAssignment_1_1");
					put(grammarAccess.getPointsAccess().getOthersAssignment_2_0(), "rule__Points__OthersAssignment_2_0");
					put(grammarAccess.getPointsAccess().getParamsAssignment_2_1(), "rule__Points__ParamsAssignment_2_1");
					put(grammarAccess.getOutcomesPointsAccess().getOutcomeAssignment_0_0(), "rule__OutcomesPoints__OutcomeAssignment_0_0");
					put(grammarAccess.getOutcomesPointsAccess().getResetValueAssignment_1(), "rule__OutcomesPoints__ResetValueAssignment_1");
					put(grammarAccess.getOutcomesPointsAccess().getPtsAssignment_2_0(), "rule__OutcomesPoints__PtsAssignment_2_0");
					put(grammarAccess.getOutcomesPointsAccess().getVarAssignment_2_1(), "rule__OutcomesPoints__VarAssignment_2_1");
					put(grammarAccess.getPointAccess().getNegativeAssignment_0(), "rule__Point__NegativeAssignment_0");
					put(grammarAccess.getPointAccess().getValueAssignment_1(), "rule__Point__ValueAssignment_1");
					put(grammarAccess.getParamsAccess().getNameAssignment_0_0(), "rule__Params__NameAssignment_0_0");
					put(grammarAccess.getParamsAccess().getValuesAssignment_1(), "rule__Params__ValuesAssignment_1");
					put(grammarAccess.getParamsAccess().getValuesAssignment_2_1(), "rule__Params__ValuesAssignment_2_1");
					put(grammarAccess.getReactionsAccess().getReactionAssignment_1(), "rule__Reactions__ReactionAssignment_1");
					put(grammarAccess.getReactionAccess().getParamsCAssignment_0(), "rule__Reaction__ParamsCAssignment_0");
					put(grammarAccess.getReactionAccess().getPointsCAssignment_1_0(), "rule__Reaction__PointsCAssignment_1_0");
					put(grammarAccess.getReactionAccess().getFeedbackAssignment_1_2(), "rule__Reaction__FeedbackAssignment_1_2");
					put(grammarAccess.getReactionAccess().getImmediateAssignment_1_3(), "rule__Reaction__ImmediateAssignment_1_3");
					put(grammarAccess.getParamConditionAccess().getParamsAssignment(), "rule__ParamCondition__ParamsAssignment");
					put(grammarAccess.getPointsConditionAccess().getKeyWdAssignment_0(), "rule__PointsCondition__KeyWdAssignment_0");
					put(grammarAccess.getPointsConditionAccess().getSignAssignment_2_0(), "rule__PointsCondition__SignAssignment_2_0");
					put(grammarAccess.getPointsConditionAccess().getValueAssignment_2_1(), "rule__PointsCondition__ValueAssignment_2_1");
					put(grammarAccess.getFeedbackModelAccess().getTriggersAssignment_1(), "rule__FeedbackModel__TriggersAssignment_1");
					put(grammarAccess.getTriggerAccess().getPerfAssignment_0(), "rule__Trigger__PerfAssignment_0");
					put(grammarAccess.getTriggerAccess().getInactivityAssignment_1(), "rule__Trigger__InactivityAssignment_1");
					put(grammarAccess.getOutcomeValueLimitAccess().getOutcomeAssignment_0(), "rule__OutcomeValueLimit__OutcomeAssignment_0");
					put(grammarAccess.getOutcomeValueLimitAccess().getSignAssignment_1(), "rule__OutcomeValueLimit__SignAssignment_1");
					put(grammarAccess.getOutcomeValueLimitAccess().getNegativeLimitAssignment_2(), "rule__OutcomeValueLimit__NegativeLimitAssignment_2");
					put(grammarAccess.getOutcomeValueLimitAccess().getLimitAssignment_3(), "rule__OutcomeValueLimit__LimitAssignment_3");
					put(grammarAccess.getOutcomeValueLimitAccess().getTriggerReactionsAssignment_4(), "rule__OutcomeValueLimit__TriggerReactionsAssignment_4");
					put(grammarAccess.getInactivityLimitAccess().getSignAssignment_1(), "rule__InactivityLimit__SignAssignment_1");
					put(grammarAccess.getInactivityLimitAccess().getLimitAssignment_2(), "rule__InactivityLimit__LimitAssignment_2");
					put(grammarAccess.getInactivityLimitAccess().getTriggerReactionsAssignment_4(), "rule__InactivityLimit__TriggerReactionsAssignment_4");
					put(grammarAccess.getBadgeModelAccess().getGenericTriggersAssignment_1(), "rule__BadgeModel__GenericTriggersAssignment_1");
					put(grammarAccess.getGenericTriggerAccess().getSimpleAssignment_0(), "rule__GenericTrigger__SimpleAssignment_0");
					put(grammarAccess.getGenericTriggerAccess().getLoAssignment_1(), "rule__GenericTrigger__LoAssignment_1");
					put(grammarAccess.getSimpleTriggerAccess().getFunctionAssignment_0(), "rule__SimpleTrigger__FunctionAssignment_0");
					put(grammarAccess.getSimpleTriggerAccess().getSignAssignment_1(), "rule__SimpleTrigger__SignAssignment_1");
					put(grammarAccess.getSimpleTriggerAccess().getNegativeLimitAssignment_2(), "rule__SimpleTrigger__NegativeLimitAssignment_2");
					put(grammarAccess.getSimpleTriggerAccess().getLimitAssignment_3(), "rule__SimpleTrigger__LimitAssignment_3");
					put(grammarAccess.getSimpleTriggerAccess().getTriggerReactionsAssignment_4(), "rule__SimpleTrigger__TriggerReactionsAssignment_4");
					put(grammarAccess.getLOTriggerAccess().getFunctionAssignment_0(), "rule__LOTrigger__FunctionAssignment_0");
					put(grammarAccess.getLOTriggerAccess().getOutcomeAssignment_1(), "rule__LOTrigger__OutcomeAssignment_1");
					put(grammarAccess.getLOTriggerAccess().getSignAssignment_2(), "rule__LOTrigger__SignAssignment_2");
					put(grammarAccess.getLOTriggerAccess().getNegativeLimitAssignment_3(), "rule__LOTrigger__NegativeLimitAssignment_3");
					put(grammarAccess.getLOTriggerAccess().getLimitAssignment_4(), "rule__LOTrigger__LimitAssignment_4");
					put(grammarAccess.getLOTriggerAccess().getTriggerReactionsAssignment_5(), "rule__LOTrigger__TriggerReactionsAssignment_5");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			uws.engage.dsl.ui.contentassist.antlr.internal.InternalAssessParser typedParser = (uws.engage.dsl.ui.contentassist.antlr.internal.InternalAssessParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AssessGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AssessGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
