/**
 * generated by Xtext
 */
package uws.engage.dsl.validation;

import uws.engage.dsl.validation.AbstractAssessValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AssessValidator extends AbstractAssessValidator {
}
