/*
* generated by Xtext
*/
package uws.chaudy.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class EngageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
