/*
* generated by Xtext
*/
package uws.chaudy;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EngageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return uws.chaudy.ui.internal.EngageActivator.getInstance().getInjector("uws.chaudy.Engage");
	}
	
}
