/*
 * generated by Xtext
 */
package uws.chaudy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EngageRuntimeModule extends uws.chaudy.AbstractEngageRuntimeModule {

}
