/*
 * generated by Xtext
 */
package uws.engage.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AssessUiModule extends uws.engage.dsl.ui.AbstractAssessUiModule {
	public AssessUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
