/*
 * generated by Xtext
 */
package uws.chaudy.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EngageUiModule extends uws.chaudy.ui.AbstractEngageUiModule {
	public EngageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
