/*
 * generated by Xtext
 */
package uws.engage.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import uws.engage.dsl.ui.internal.AssessActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AssessExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AssessActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AssessActivator.getInstance().getInjector(AssessActivator.UWS_ENGAGE_DSL_ASSESS);
	}
	
}
