/*
* generated by Xtext
*/
package uws.engage.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AssessStandaloneSetup extends AssessStandaloneSetupGenerated{

	public static void doSetup() {
		new AssessStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

