/*
 * generated by Xtext
 */
package uws.engage.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AssessRuntimeModule extends uws.engage.dsl.AbstractAssessRuntimeModule {

}
