/*
* generated by Xtext
*/
package uws.chaudy.ui.contentassist;

import uws.chaudy.ui.contentassist.AbstractEngageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EngageProposalProvider extends AbstractEngageProposalProvider {

}
